# vim: set filetype=dockerfile:
FROM alpine:3.18.3
RUN apk add curl bash sudo git vim
RUN adduser -u 1000 -G wheel -D foo
RUN sed -i 's|# %wheel ALL=(ALL:ALL) NOPASSWD|%wheel ALL=(ALL:ALL) NOPASSWD|' /etc/sudoers
USER foo
RUN mkdir /home/foo/workspace
WORKDIR /home/foo/workspace
RUN curl -sSfL -O https://raw.githubusercontent.com/khulnasoftproj/khulnasoft-installer/v2.1.2/khulnasoft-installer
RUN echo "411caf1b5fcef4f5e74aa2a9fe99182ea13ab93ecd8ed4a983a7cff9f08edab9  khulnasoft-installer" | sha256sum -c
RUN chmod +x khulnasoft-installer
RUN ./khulnasoft-installer -v "v2.1.2"
ENV PATH=/home/foo/.local/share/khulnasoftproj-khulnasoft/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
