---
name: Debug with action-tmate
on:
  workflow_dispatch:
    inputs:
      runs-on:
        required: false
        default: windows-latest
      pr_number:
        required: false
      ref:
        required: false
permissions: {}
jobs:
  action-tmate:
    runs-on: ${{inputs.runs-on}}
    steps:
      - uses: actions/checkout@v3 # v3.5.3
        with:
          ref: ${{inputs.ref}}

      - run: gh pr checkout "${{inputs.pr_number}}"
        if: inputs.pr_number != ''
        env:
          GITHUB_TOKEN: ${{github.token}}
      - uses: khulnasoftproj/khulnasoft-installer@v2.1.2 # v2.1.2
        with:
          khulnasoft_version: v2.10.1
        env:
          KHULNASOFT_GITHUB_TOKEN: ${{github.token}}
      - uses: actions/setup-go@v4.1.0 # v4.1.0
        with:
          go-version: 1.21.0

      # The default vim doesn't work well, so we install the latest vim ourselves.
      - uses: rhysd/action-setup-vim@v1.2.15 # v1.2.15

      - uses: mxschmitt/action-tmate@v3.14 # v3.14
        with:
          limit-access-to-actor: true # SSH Key is required
        env:
          GITHUB_TOKEN: ${{github.token}} # Pass GitHub Token to shell session
