---
name: Integration Test on macOS
on: workflow_dispatch

env:
  KHULNASOFT_LOG_COLOR: always

permissions: {}

jobs:
  integration-test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.5.3 # v3.5.3
      - uses: actions/setup-go@v4.1.0# v4.1.0
        with:
          go-version: 1.21.0
          cache: true
      - run: go install ./cmd/khulnasoft
      - run: echo "${XDG_DATA_HOME:-$HOME/.local/share}/khulnasoftproj-khulnasoft/bin" >> "$GITHUB_PATH"
      - run: khulnasoft policy allow
      - run: khulnasoft i -l
        working-directory: tests/macos
        env:
          GITHUB_TOKEN: ${{github.token}}

      - run: aws-vault --version
        working-directory: tests/macos
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: khulnasoft gr 99designs/aws-vault
        env:
          GITHUB_TOKEN: ${{github.token}}

      - run: s3deploy -V
        working-directory: tests/macos
        env:
          GITHUB_TOKEN: ${{github.token}}
      - run: khulnasoft gr bep/s3deploy
        env:
          GITHUB_TOKEN: ${{github.token}}
