---
name: Release
on:
  push:
    tags: [v*]
permissions: {}
jobs:
  release:
    uses: sulaiman-coder/go-release-workflow/.github/workflows/release.yaml@8e5a34c2b4e3c2a7d5e22346ef8328d2c3d0713e # v0.4.3
    with:
      homebrew: true
      go-version: 1.21.0
      khulnasoft_policy_allow: true
      khulnasoft_version: v2.10.1
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
    permissions:
      contents: write
      id-token: write
      actions: read
