---
name: test
on: pull_request
permissions: {}
jobs:
  path-filter:
    # Get changed files to filter jobs
    outputs:
      update-khulnasoft-checksums: ${{steps.changes.outputs.update-khulnasoft-checksums}}
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      ghalint: ${{steps.changes.outputs.ghalint}}
      go-mod-tidy: ${{steps.changes.outputs.go-mod-tidy}}
      test-docker: ${{steps.changes.outputs.test-docker}}
      test-docker-prebuilt: ${{steps.changes.outputs.test-docker-prebuilt}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@v2.11.1 # v2.11.1
        id: changes
        with:
          filters: |
            update-khulnasoft-checksums:
              - khulnasoft/khulnasoft.yaml
              - khulnasoft/imports/*.yaml
              - khulnasoft/khulnasoft-checksums.json
              - .github/workflows/test.yaml
              - .github/workflows/wc-update-khulnasoft-checksums.yaml
            renovate-config-validator:
              - renovate.json5
              - .github/workflows/test.yaml
              - .github/workflows/wc-renovate-config-validator.yaml
            ghalint:
              - .github/workflows/*.yaml
              - khulnasoft/khulnasoft.yaml
              - khulnasoft/imports/ghalint.yaml
              - ghalint.yaml
            go-mod-tidy:
              - go.mod
              - go.sum
              - "**.go"
              - .github/workflows/test.yaml
              - .github/workflows/wc-go-mod-tidy.yaml
            test-docker:
              - Dockerfile
              - .github/workflows/wc-test.yaml
            test-docker-prebuilt:
              - Dockerfile-prebuilt
              - .github/workflows/wc-test-docker-prebuilt.yaml

  enable-automerge:
    uses: ./.github/workflows/wc-enable-auto-merge.yaml
    needs:
      - status-check
    permissions:
      contents: write # For enable automerge
      pull-requests: write # For enable automerge
    # "! failure() && ! cancelled()" is required. success() returns false if dependent jobs are skipped.
    # https://github.com/community/community/discussions/45058
    # By default success() is used so we have to override success() by "! failure() && ! cancelled()"
    if: |
      ! failure() && ! cancelled() && github.event.pull_request.user.login == 'renovate[bot]' && contains(github.event.pull_request.body, ' **Automerge**: Enabled.')
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}

  status-check:
    uses: ./.github/workflows/wc-status-check.yaml
    permissions: {}
    if: failure()
    needs:
      - renovate-config-validator
      - update-khulnasoft-checksums
      - ghalint
      - test
      - test-docker-prebuilt
      - integration-test
      - go-mod-tidy

  renovate-config-validator:
    uses: ./.github/workflows/wc-renovate-config-validator.yaml
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  update-khulnasoft-checksums:
    needs: path-filter
    if: needs.path-filter.outputs.update-khulnasoft-checksums == 'true'
    uses: ./.github/workflows/wc-update-khulnasoft-checksums.yaml
    permissions:
      contents: read
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}

  ghalint:
    needs: path-filter
    if: needs.path-filter.outputs.ghalint == 'true'
    uses: ./.github/workflows/wc-ghalint.yaml
    permissions: {}

  test:
    uses: ./.github/workflows/wc-test.yaml
    needs: path-filter
    permissions: {}
    with:
      docker_is_changed: ${{needs.path-filter.outputs.test-docker == 'true'}}

  test-docker-prebuilt:
    uses: ./.github/workflows/wc-test-docker-prebuilt.yaml
    needs: path-filter
    if: needs.path-filter.outputs.test-docker-prebuilt == 'true'
    permissions: {}

  go-mod-tidy:
    uses: ./.github/workflows/wc-go-mod-tidy.yaml
    needs: path-filter
    if: needs.path-filter.outputs.go-mod-tidy == 'true'
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
    permissions:
      contents: read

  integration-test:
    uses: ./.github/workflows/wc-integration-test.yaml
    permissions: {}
