---
name: test-docker-prebuilt
on: workflow_call
jobs:
  test-docker:
    # Test Dockerfile
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v3 # v3.5.3
      - run: docker build -t khulnasoftproj-khulnasoft-dev -f Dockerfile-prebuilt .
