---
name: Integration Test on Windows
on:
  workflow_dispatch:
    inputs:
      khulnasoft_version:
        required: false
      pr_number:
        required: false
      ref:
        required: false

env:
  KHULNASOFT_GLOBAL_CONFIG: ${{ github.workspace }}/tests/main/khulnasoft-global.yaml:${{ github.workspace }}/tests/main/khulnasoft-global-2.yaml
  KHULNASOFT_LOG_COLOR: always
  KHULNASOFT_LOG_LEVEL: debug

permissions: {}

jobs:
  integration-test-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    env:
      GITHUB_TOKEN: ${{github.token}}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{inputs.ref}}
      - run: gh pr checkout "${{inputs.pr_number}}"
        if: inputs.pr_number != ''
        env:
          GITHUB_TOKEN: ${{github.token}}

      - uses: khulnasoftproj/khulnasoft-installer@36dc5833b04eb63f06e3bb818aa6b7a6e6db99a9 # v2.1.2
        if: inputs.khulnasoft_version != ''
        with:
          khulnasoft_version: ${{inputs.khulnasoft_version}}

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        if: inputs.khulnasoft_version == ''
        with:
          go-version: 1.21.0
          cache: true
      - run: go install ./cmd/khulnasoft
        if: inputs.khulnasoft_version == ''

      - run: echo "$HOME/AppData/Local/khulnasoftproj-khulnasoft/bin" >> "$GITHUB_PATH"
      - run: khulnasoft policy allow
      - run: echo "KHULNASOFT_GLOBAL_CONFIG=$PWD/tests/main/khulnasoft-global.yaml:$PWD/tests/main/khulnasoft-global-2.yaml" >> "$GITHUB_ENV"
      - run: echo "standard,kubernetes-sigs/kind" | khulnasoft g -f -
      - run: echo "x-motemen/ghq" | khulnasoft g -f -
      - run: khulnasoft g x-motemen/ghq khulnasoftproj/khulnasoft-installer
      - run: echo cli/cli | khulnasoft g -f - x-motemen/ghq khulnasoftproj/khulnasoft-installer

      - run: khulnasoft list
      - run: khulnasoft update-checksum
        working-directory: tests/main
      - run: khulnasoft i -l -a
        working-directory: tests/main
      - run: cmdx -v
        working-directory: tests/main
      - run: khulnasoft i
        working-directory: tests/main
      - run: khulnasoft which golangci-lint
        working-directory: tests/main
      - run: khulnasoft which go
      - run: golangci-lint version
      - run: kind version
        working-directory: tests/main
      - run: kind version
      - run: restic version
        env:
          KHULNASOFT_PROGRESS_BAR: "true"
      - run: migrate -version
      - run: ghq -version
      - run: gh version
      - run: khulnasoft -c tests/main/khulnasoft-global.yaml g local,kubernetes-sigs/kustomize
      - run: github-compare -v
      - run: helm version
      - run: terrafmt version

      - run: khulnasoft g -i sulaiman-coder/tfcmt
        working-directory: tests/main
      - run: git diff khulnasoft.yaml
        working-directory: tests/main

      - name: "Test generate-registry"
        run: khulnasoft gr cli/cli
      - name: "Test generate-registry (rust)"
        run: khulnasoft gr XAMPPRocky/tokei

      # Test if global configuration files are read in `khulnasoft list` and `khulnasoft g`
      - run: khulnasoft g sulaiman-coder/cmdx
        working-directory: ${{ env.HOME }}
      - run: khulnasoft list
        working-directory: ${{ env.HOME }}

      - name: test khulnasoft cp
        run: khulnasoft cp actionlint golangci-lint
      - name: test khulnasoft cp
        run: dist/actionlint -version
      - name: test khulnasoft cp
        run: dist/golangci-lint version

      - name: Test update-khulnasoft
        run: khulnasoft update-khulnasoft

  integration-test-windows-pwsh:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{github.token}}
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{inputs.ref}}
      - run: gh pr checkout "${{inputs.pr_number}}"
        if: inputs.pr_number != ''
        env:
          GITHUB_TOKEN: ${{github.token}}

      - uses: khulnasoftproj/khulnasoft-installer@36dc5833b04eb63f06e3bb818aa6b7a6e6db99a9 # v2.1.2
        if: inputs.khulnasoft_version != ''
        with:
          khulnasoft_version: ${{inputs.khulnasoft_version}}

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        if: inputs.khulnasoft_version == ''
        with:
          go-version: 1.21.0
          cache: true
      - run: go install ./cmd/khulnasoft
        if: inputs.khulnasoft_version == ''

      - run: khulnasoft policy allow
      - run: echo "$HOME\AppData\Local\khulnasoftproj-khulnasoft\bat" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: echo "KHULNASOFT_GLOBAL_CONFIG=$PWD\tests\main\khulnasoft-global.yaml;$PWD\tests\main\khulnasoft-global-2.yaml" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - run: echo "standard,kubernetes-sigs/kind" | khulnasoft g -f -
      - run: echo "x-motemen/ghq" | khulnasoft g -f -
      - run: khulnasoft g x-motemen/ghq khulnasoftproj/khulnasoft-installer
      - run: echo cli/cli | khulnasoft g -f - x-motemen/ghq khulnasoftproj/khulnasoft-installer

      - run: khulnasoft list
      - run: khulnasoft update-checksum
        working-directory: tests/main
      - run: khulnasoft i -l -a
        working-directory: tests/main
      - run: cmdx -v
        working-directory: tests/main
      - run: khulnasoft i
        working-directory: tests/main
      - run: khulnasoft which golangci-lint
        working-directory: tests/main
      - run: khulnasoft which go
      - run: golangci-lint version
      - run: kind version
        working-directory: tests/main
      - run: kind version
      - run: restic version
        env:
          KHULNASOFT_PROGRESS_BAR: "true"
      - run: migrate -version
      - run: ghq -version
      - run: gh version
      - run: khulnasoft -c tests/main/khulnasoft-global.yaml g local,kubernetes-sigs/kustomize
      - run: github-compare -v
      - run: terrafmt version
      - run: helm version

      - run: khulnasoft g -i sulaiman-coder/tfcmt
        working-directory: tests/main
      - run: git diff khulnasoft.yaml
        working-directory: tests/main

      - name: "Test generate-registry"
        run: khulnasoft gr cli/cli
      - name: "Test generate-registry (rust)"
        run: khulnasoft gr XAMPPRocky/tokei

      # Test if global configuration files are read in `khulnasoft list` and `khulnasoft g`
      - run: khulnasoft g sulaiman-coder/cmdx
        working-directory: ${{env.HOME}}
      - run: khulnasoft list
        working-directory: ${{env.HOME}}

      - name: test khulnasoft cp
        run: khulnasoft cp actionlint golangci-lint
      - name: test khulnasoft cp
        run: dist/actionlint -version
      - name: test khulnasoft cp
        run: dist/golangci-lint version

      - name: Test update-khulnasoft
        run: khulnasoft update-khulnasoft
